### ISSUE TITLE
Config saving error

### ISSUE THREAD

**Issue by blongnh** [Andosius/valorant-exporter#1]
Hi! I got an error trying to save my config.
I had to manually create the \data folder in the same folder of valorant-exporter for it to work.

```Welcome! This is YOUR Valorant settings manager!
In order to continue, you have to choose between these options:

> 1) Save your current settings (remember current time, it will be the filename)
> 2) Push saved settings to the server

Choose your desired option: 1

cfg.WriteConfigToFile:2
open data\08_10_2022-10_20_43.json: The system cannot find the path specified.
** Programm quits in 10 seconds!```

**Comment by Andosius** [comment]
Hey,

thanks for reporting this issue.
I already located the problem and I‘ll fix it later.

For whatever reason I integrated an existence check in option number 2s core method and did not think about moving it to a seperate check.

https://github.com/Andosius/valorant-exporter/blob/38eb38af1e57d246c02e982e8a4f606d845c4433/main.go#L38
https://github.com/Andosius/valorant-exporter/blob/38eb38af1e57d246c02e982e8a4f606d845c4433/models/config_manager.go#L32

Have a great day! :)
